# Generated by Django 5.1.7 on 2025-06-16 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('shop_description', models.TextField(blank=True)),
                ('business_type', models.CharField(choices=[('individual', 'Individual/Sole Proprietor'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('llc', 'LLC')], default='individual', max_length=20)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_address', models.TextField()),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/')),
                ('shop_banner', models.ImageField(blank=True, null=True, upload_to='shops/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
