# Generated by Django 5.1.7 on 2025-06-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order__original_total_alter_order_email_orderitem'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='seller.sellerprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
