# Generated by Django 5.1.7 on 2025-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
